
### Get All Projects
GET http://localhost:3000/api/v1/projects
Content-Type: application/json


### Get Project by ID
GET http://localhost:3000/api/v1/project/5ac2b8f4-828a-4488-ad20-f900ed10ab79
Content-Type: application/json


### Create New Project
POST http://localhost:3000/api/v1/project
Content-Type: application/json

{
  "projectName": "Project X",
  "bobot": 0.5,
  "deadline": "2025-12-31",
  "status": "ONPROGRESS",
  "projectCollaborator": [
    {
      "userId": "05130cd0-b8d7-47ff-bd67-42586148c343",
      "isProjectManager": true
    },
    {
      "userId": "16734319-7d27-4a51-a32d-13b75d19f1d6",
      "isProjectManager": false
    }
  ]
}

###

### Update Project
PATCH http://localhost:3000/api/v1/project/5ac2b8f4-828a-4488-ad20-f900ed10ab79
Content-Type: application/json

{
  "projectName": "Updated Project Name",
  "bobot": 0.85,
  "deadline": "2026-06-15",
  "status": "DONE",
  "projectCollaborator": [
    {
      "userId": "f48b22e5-7879-499f-bc41-192146f5839d",
      "isProjectManager": false
    }
  ]
}

###

### Delete Project 
DELETE http://localhost:3000/api/v1/project/5e0e63fb-0df8-4888-9abc-87242c2e9023
Content-Type: application/json
